name: Issue Comment Handler

on:
    issues:
        types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
    handle_issue_comment:
        runs-on: ubuntu-latest
        steps:
            - name: "dump github context"
              run: echo '${{ toJson(github.event)}}' | jq
              shell: bash
            - name: Create comment
              uses: peter-evans/create-or-update-comment@v5
              with:
                issue-number: '${{ github.event.issue.number }}'
                body: |
                  This is a multi-line test comment
                  - With GitHub **Markdown** :sparkles:
                  - Created by [create-or-update-comment][1]
      
                  [1]: https://github.com/peter-evans/create-or-update-comment
                reactions: '+1'

    Comment_with_api:
        runs-on: ubuntu-latest
        steps:
            - name: Create comment with API
              run: |
               gh api -X POST \
                 https://api.github.com/repos/${Orgnization}/${Repository}/issues/${issue_number}/comments \
                    -f body="This is a comment created with the GitHub CLI API"

              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                Orgnization: ${{ github.event.repository.owner.login }}
                Repository: ${{ github.event.repository.name }}
                issue_number: ${{ github.event.issue.number }}